ReadME
data_lake_extraction
├── Data Extraction
├── EDA
│   ├── Customers EDA
│   ├── Products EDA
│   ├── Categories EDA
│   ├── Stores EDA
│   ├── Staffs EDA
│   ├── Stocks EDA
│   └── Brands EDA
├── Actions
│   └── Products
│       └── Remove Duplicates
├── Extra Checks
└── Export Files

# Data Extraction

In [1]:
import pandas as pd 
from glob import glob
import os
import time

In [2]:
files = glob("../data/raw/*.csv")
print(len(files))
print(files)

7
['../data/raw\\brands.csv', '../data/raw\\categories.csv', '../data/raw\\customers.csv', '../data/raw\\products.csv', '../data/raw\\staffs.csv', '../data/raw\\stocks.csv', '../data/raw\\stores.csv']

In [3]:
df_names = []

In [4]:
for i in files :
    # import file 
    df = pd.read_csv(i)

    # add time and source
    df["extraction_timestamp"] = int(time.time())
    df["extraction_date"] = pd.to_datetime(df["extraction_timestamp"], unit="s")
    df["data_source"] = "Data Lake"
    
    #change name of df 
    file_name =os.path.basename(i)
    file_name = file_name.replace(".csv" , "")
    globals()[f"df_{file_name}"] = df

    # add to list
    df_names.append(f"df_{file_name}")

    #print new name
    print(f"Created: df_{file_name}")

Created: df_brands
Created: df_categories
Created: df_customers
Created: df_products
Created: df_staffs
Created: df_stocks
Created: df_stores

In [5]:
for i in df_names:
    
    df = globals()[i]
    length = df.shape
    nulls = df.isnull().sum().sum()
    
    print(f"{i}  ")
    print(f"   length : {length}")
    print(f"   nulls : {nulls}")
    print("-"*30)

df_brands
   length : (9, 5)
   nulls : 0
------------------------------
df_categories
   length : (7, 5)
   nulls : 0
------------------------------
df_customers
   length : (1445, 12)
   nulls : 1267
------------------------------
df_products
   length : (334, 9)
   nulls : 0
------------------------------
df_staffs
   length : (10, 11)
   nulls : 6
------------------------------
df_stocks
   length : (939, 6)
   nulls : 0
------------------------------
df_stores
   length : (3, 11)
   nulls : 2
------------------------------

# EDA

## Customers EDA

In [6]:
df_customers

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,extraction_timestamp,extraction_date,data_source
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127,1774518425,2026-03-26 09:47:05,Data Lake
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008,1774518425,2026-03-26 09:47:05,Data Lake
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278,1774518425,2026-03-26 09:47:05,Data Lake
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553,1774518425,2026-03-26 09:47:05,Data Lake
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820,1774518425,2026-03-26 09:47:05,Data Lake
...,...,...,...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,NaN,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301,1774518425,2026-03-26 09:47:05,Data Lake
1441,1442,Cassie,Cline,NaN,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201,1774518425,2026-03-26 09:47:05,Data Lake
1442,1443,Lezlie,Lamb,NaN,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722,1774518425,2026-03-26 09:47:05,Data Lake
1443,1444,Ivette,Estes,NaN,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424,1774518425,2026-03-26 09:47:05,Data Lake
1444,1445,Ester,Acevedo,NaN,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [7]:
# table summary
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           1445 non-null   int64
 1   first_name            1445 non-null   str
 2   last_name             1445 non-null   str
 3   phone                 178 non-null    str
 4   email                 1445 non-null   str
 5   street                1445 non-null   str
 6   city                  1445 non-null   str
 7   state                 1445 non-null   str
 8   zip_code              1445 non-null   int64
 9   extraction_timestamp  1445 non-null   int64
 10  extraction_date       1445 non-null   datetime64[s]
 11  data_source           1445 non-null   str
dtypes: datetime64[s](1), int64(3), str(8)
memory usage: 135.6 KB

In [8]:
# numeris vars summary
df_customers.describe()

       customer_id      zip_code  extraction_timestamp      extraction_date
count  1445.000000   1445.000000          1.445000e+03                 1445
mean    723.000000  34200.015225          1.774518e+09  2026-03-26 09:47:05
min       1.000000  10002.000000          1.774518e+09  2026-03-26 09:47:05
25%     362.000000  11419.000000          1.774518e+09  2026-03-26 09:47:05
50%     723.000000  11967.000000          1.774518e+09  2026-03-26 09:47:05
75%    1084.000000  76110.000000          1.774518e+09  2026-03-26 09:47:05
max    1445.000000  95993.000000          1.774518e+09  2026-03-26 09:47:05
std     417.279882  34733.933551          0.000000e+00                  NaN

In [9]:
rows,cols=df_customers.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 1445
num of columns = 12

### Null Checks

In [10]:
t_nulls = df_customers.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_customers.isna().sum()

total_num_of_nulls = 1267
====================
nulls per column

customer_id                0
first_name                 0
last_name                  0
phone                   1267
email                      0
street                     0
city                       0
state                      0
zip_code                   0
extraction_timestamp       0
extraction_date            0
data_source                0
dtype: int64

### Duplicate Validation ( Rows )

In [11]:
df_customers.duplicated().sum()

np.int64(0)

In [12]:
df_customers[df_customers.duplicated()]

Empty DataFrame
Columns: [customer_id, first_name, last_name, phone, email, street, city, state, zip_code, extraction_timestamp, extraction_date, data_source]
Index: []

### Unique Values

In [13]:
df_customers.nunique()

customer_id             1445
first_name              1265
last_name                753
phone                    178
email                   1445
street                  1445
city                     195
state                      3
zip_code                 195
extraction_timestamp       1
extraction_date            1
data_source                1
dtype: int64

In [14]:
df_customers["customer_id"].duplicated().sum()

np.int64(0)

In [15]:
for col in df_customers.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_customers[col].value_counts().head(5))
    print("\n")

==================================================
Column: customer_id
--------------------------------------------------
customer_id
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64


==================================================
Column: first_name
--------------------------------------------------
first_name
Genoveva    3
Aleta       3
Jamaal      3
Diana       3
Lorrie      3
Name: count, dtype: int64


==================================================
Column: last_name
--------------------------------------------------
last_name
Larson    7
Hardin    6
Vega      6
Melton    6
Joyner    6
Name: count, dtype: int64


==================================================
Column: phone
--------------------------------------------------
phone
(916) 381-6003    1
(716) 986-3359    1
(516) 583-7761    1
(212) 945-8823    1
(562) 215-2907    1
Name: count, dtype: int64


==================================================
Column: email
--------------------------------------------------
email
debra.burks@yahoo.com      1
kasha.todd@yahoo.com       1
tameka.fisher@aol.com      1
daryl.spence@aol.com       1
charolette.rice@msn.com    1
Name: count, dtype: int64


==================================================
Column: street
--------------------------------------------------
street
9273 Thorne Ave.         1
910 Vine Street          1
769C Honey Creek St.     1
988 Pearl Lane           1
107 River Dr.            1
Name: count, dtype: int64


==================================================
Column: city
--------------------------------------------------
city
Mount Vernon    20
Scarsdale       17
Ballston Spa    17
Canandaigua     14
Longview        13
Name: count, dtype: int64


==================================================
Column: state
--------------------------------------------------
state
NY    1019
CA     284
TX     142
Name: count, dtype: int64


==================================================
Column: zip_code
--------------------------------------------------
zip_code
10550    20
10583    17
12020    17
14424    14
75604    13
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    1445
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    1445
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    1445
Name: count, dtype: int64

## Products EDA

In [16]:
df_products

,product_id,product_name,brand_id,category_id,model_year,list_price,extraction_timestamp,extraction_date,data_source
0,1,Trek 820 - 2016,9,6,2016,379.99,1774518425,2026-03-26 09:47:05,Data Lake
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99,1774518425,2026-03-26 09:47:05,Data Lake
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99,1774518425,2026-03-26 09:47:05,Data Lake
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99,1774518425,2026-03-26 09:47:05,Data Lake
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99,1774518425,2026-03-26 09:47:05,Data Lake
...,...,...,...,...,...,...,...,...,...
329,317,Trek Checkpoint ALR 5 - 2019,9,7,2019,1999.99,1774518425,2026-03-26 09:47:05,Data Lake
330,318,Trek Checkpoint ALR 5 Women's - 2019,9,7,2019,1999.99,1774518425,2026-03-26 09:47:05,Data Lake
331,319,Trek Checkpoint SL 5 Women's - 2019,9,7,2019,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
332,320,Trek Checkpoint SL 6 - 2019,9,7,2019,3799.99,1774518425,2026-03-26 09:47:05,Data Lake
333,321,Trek Checkpoint ALR Frameset - 2019,9,7,2019,3199.99,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [17]:
# table summary
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            334 non-null    int64
 1   product_name          334 non-null    str
 2   brand_id              334 non-null    int64
 3   category_id           334 non-null    int64
 4   model_year            334 non-null    int64
 5   list_price            334 non-null    float64
 6   extraction_timestamp  334 non-null    int64
 7   extraction_date       334 non-null    datetime64[s]
 8   data_source           334 non-null    str
dtypes: datetime64[s](1), float64(1), int64(5), str(2)
memory usage: 23.6 KB

In [18]:
# numeris vars summary
df_products.describe()

,product_id,brand_id,category_id,model_year,list_price,extraction_timestamp,extraction_date
count,334.000000,334.000000,334.000000,334.000000,334.000000,3.340000e+02,334
mean,160.886228,5.383234,3.964072,2017.580838,1498.053024,1.774518e+09,2026-03-26 09:47:05
min,1.000000,1.000000,1.000000,2016.000000,89.990000,1.774518e+09,2026-03-26 09:47:05
25%,81.250000,1.000000,2.000000,2017.000000,416.990000,1.774518e+09,2026-03-26 09:47:05
50%,161.500000,7.000000,3.000000,2018.000000,749.990000,1.774518e+09,2026-03-26 09:47:05
75%,241.750000,9.000000,6.000000,2018.000000,2299.990000,1.774518e+09,2026-03-26 09:47:05
max,321.000000,9.000000,7.000000,2019.000000,11999.990000,1.774518e+09,2026-03-26 09:47:05
std,93.439960,3.721113,2.193061,0.674097,1600.829625,0.000000e+00,NaN

In [19]:
rows,cols=df_products.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 334
num of columns = 9

### Null Checks

In [20]:
t_nulls = df_products.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_products.isna().sum()

total_num_of_nulls = 0
====================
nulls per column

product_id              0
product_name            0
brand_id                0
category_id             0
model_year              0
list_price              0
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

### Duplicate Validation ( Rows )

In [21]:
df_products.duplicated().sum()

np.int64(13)

In [22]:
df_products[df_products.duplicated()]

,product_id,product_name,brand_id,category_id,model_year,list_price,extraction_timestamp,extraction_date,data_source
15,12,Electra Townie Original 21D - 2016,1,3,2016,549.99,1774518425,2026-03-26 09:47:05,Data Lake
16,13,Electra Cruiser 1 (24-Inch) - 2016,1,3,2016,269.99,1774518425,2026-03-26 09:47:05,Data Lake
17,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,1,3,2016,269.99,1774518425,2026-03-26 09:47:05,Data Lake
102,92,Haro Shredder 20 - 2017,2,1,2017,209.99,1774518425,2026-03-26 09:47:05,Data Lake
103,93,Haro Shredder 20 Girls - 2017,2,1,2017,209.99,1774518425,2026-03-26 09:47:05,Data Lake
104,94,Haro Shredder Pro 20 - 2017,2,1,2017,249.99,1774518425,2026-03-26 09:47:05,Data Lake
197,188,Trek XM700+ Lowstep - 2018,9,5,2018,3499.99,1774518425,2026-03-26 09:47:05,Data Lake
198,189,Trek Lift+ Lowstep - 2018,9,5,2018,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
199,190,Trek Dual Sport+ - 2018,9,5,2018,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
303,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,1,1,2018,319.99,1774518425,2026-03-26 09:47:05,Data Lake
304,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,1,1,2018,369.99,1774518425,2026-03-26 09:47:05,Data Lake
305,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,1,1,2018,319.99,1774518425,2026-03-26 09:47:05,Data Lake
306,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,1,1,2018,369.99,1774518425,2026-03-26 09:47:05,Data Lake

In [23]:
len(df_products[df_products.duplicated(keep=False)])

26

In [24]:
df_products[df_products.duplicated(keep=False)].sort_values(by="product_id")

,product_id,product_name,brand_id,category_id,model_year,list_price,extraction_timestamp,extraction_date,data_source
11,12,Electra Townie Original 21D - 2016,1,3,2016,549.99,1774518425,2026-03-26 09:47:05,Data Lake
15,12,Electra Townie Original 21D - 2016,1,3,2016,549.99,1774518425,2026-03-26 09:47:05,Data Lake
12,13,Electra Cruiser 1 (24-Inch) - 2016,1,3,2016,269.99,1774518425,2026-03-26 09:47:05,Data Lake
16,13,Electra Cruiser 1 (24-Inch) - 2016,1,3,2016,269.99,1774518425,2026-03-26 09:47:05,Data Lake
13,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,1,3,2016,269.99,1774518425,2026-03-26 09:47:05,Data Lake
17,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,1,3,2016,269.99,1774518425,2026-03-26 09:47:05,Data Lake
94,92,Haro Shredder 20 - 2017,2,1,2017,209.99,1774518425,2026-03-26 09:47:05,Data Lake
102,92,Haro Shredder 20 - 2017,2,1,2017,209.99,1774518425,2026-03-26 09:47:05,Data Lake
95,93,Haro Shredder 20 Girls - 2017,2,1,2017,209.99,1774518425,2026-03-26 09:47:05,Data Lake
103,93,Haro Shredder 20 Girls - 2017,2,1,2017,209.99,1774518425,2026-03-26 09:47:05,Data Lake
96,94,Haro Shredder Pro 20 - 2017,2,1,2017,249.99,1774518425,2026-03-26 09:47:05,Data Lake
104,94,Haro Shredder Pro 20 - 2017,2,1,2017,249.99,1774518425,2026-03-26 09:47:05,Data Lake
193,188,Trek XM700+ Lowstep - 2018,9,5,2018,3499.99,1774518425,2026-03-26 09:47:05,Data Lake
197,188,Trek XM700+ Lowstep - 2018,9,5,2018,3499.99,1774518425,2026-03-26 09:47:05,Data Lake
194,189,Trek Lift+ Lowstep - 2018,9,5,2018,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
198,189,Trek Lift+ Lowstep - 2018,9,5,2018,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
195,190,Trek Dual Sport+ - 2018,9,5,2018,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
199,190,Trek Dual Sport+ - 2018,9,5,2018,2799.99,1774518425,2026-03-26 09:47:05,Data Lake
299,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,1,1,2018,319.99,1774518425,2026-03-26 09:47:05,Data Lake
303,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,1,1,2018,319.99,1774518425,2026-03-26 09:47:05,Data Lake
300,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,1,1,2018,369.99,1774518425,2026-03-26 09:47:05,Data Lake
304,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,1,1,2018,369.99,1774518425,2026-03-26 09:47:05,Data Lake
301,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,1,1,2018,319.99,1774518425,2026-03-26 09:47:05,Data Lake
305,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,1,1,2018,319.99,1774518425,2026-03-26 09:47:05,Data Lake
302,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,1,1,2018,369.99,1774518425,2026-03-26 09:47:05,Data Lake
306,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,1,1,2018,369.99,1774518425,2026-03-26 09:47:05,Data Lake

### Unique Values

In [25]:
df_products.nunique()

product_id              321
product_name            291
brand_id                  9
category_id               7
model_year                4
list_price              106
extraction_timestamp      1
extraction_date           1
data_source               1
dtype: int64

In [26]:
for col in df_products.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_products[col].value_counts())
    print("\n")

==================================================
Column: product_id
--------------------------------------------------
product_id
12     2
13     2
14     2
92     2
93     2
      ..
317    1
318    1
319    1
320    1
321    1
Name: count, Length: 321, dtype: int64


==================================================
Column: product_name
--------------------------------------------------
product_name
Electra Townie Original 21D - 2016               3
Electra Cruiser 1 (24-Inch) - 2016               3
Electra Girl's Hawaii 1 (16-inch) - 2015/2016    3
Electra Townie Go! 8i - 2017/2018                3
Electra Townie Original 7D EQ - 2016             2
                                                ..
Trek Checkpoint ALR 5 - 2019                     1
Trek Checkpoint ALR 5 Women's - 2019             1
Trek Checkpoint SL 5 Women's - 2019              1
Trek Checkpoint SL 6 - 2019                      1
Trek Checkpoint ALR Frameset - 2019              1
Name: count, Length: 291, dtype: int64


==================================================
Column: brand_id
--------------------------------------------------
brand_id
9    138
1    125
8     25
7     23
2     13
3      3
4      3
6      3
5      1
Name: count, dtype: int64


==================================================
Column: category_id
--------------------------------------------------
category_id
3    81
1    66
6    60
7    60
2    30
5    27
4    10
Name: count, dtype: int64


==================================================
Column: model_year
--------------------------------------------------
model_year
2018    211
2017     88
2016     29
2019      6
Name: count, dtype: int64


==================================================
Column: list_price
--------------------------------------------------
list_price
749.99     18
319.99     15
899.99     13
3199.99    10
269.99      9
           ..
399.99      1
159.99      1
389.99      1
1699.99     1
3799.99     1
Name: count, Length: 106, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    334
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    334
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    334
Name: count, dtype: int64

Action Needed
>> Remove Duplicated Rows

## Categories EDA

In [27]:
df_categories

,category_id,category_name,extraction_timestamp,extraction_date,data_source
0,1,Children Bicycles,1774518425,2026-03-26 09:47:05,Data Lake
1,2,Comfort Bicycles,1774518425,2026-03-26 09:47:05,Data Lake
2,3,Cruisers Bicycles,1774518425,2026-03-26 09:47:05,Data Lake
3,4,Cyclocross Bicycles,1774518425,2026-03-26 09:47:05,Data Lake
4,5,Electric Bikes,1774518425,2026-03-26 09:47:05,Data Lake
5,6,Mountain Bikes,1774518425,2026-03-26 09:47:05,Data Lake
6,7,Road Bikes,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [28]:
# table summary
df_categories.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   category_id           7 non-null      int64
 1   category_name         7 non-null      str
 2   extraction_timestamp  7 non-null      int64
 3   extraction_date       7 non-null      datetime64[s]
 4   data_source           7 non-null      str
dtypes: datetime64[s](1), int64(2), str(2)
memory usage: 412.0 bytes

In [29]:
# numeris vars summary
df_categories.describe()

       category_id  extraction_timestamp      extraction_date
count     7.000000          7.000000e+00                    7
mean      4.000000          1.774518e+09  2026-03-26 09:47:05
min       1.000000          1.774518e+09  2026-03-26 09:47:05
25%       2.500000          1.774518e+09  2026-03-26 09:47:05
50%       4.000000          1.774518e+09  2026-03-26 09:47:05
75%       5.500000          1.774518e+09  2026-03-26 09:47:05
max       7.000000          1.774518e+09  2026-03-26 09:47:05
std       2.160247          0.000000e+00                  NaN

In [30]:
rows,cols=df_categories.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 7
num of columns = 5

### Null Checks

In [31]:
t_nulls = df_categories.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_categories.isna().sum()

total_num_of_nulls = 0
====================
nulls per column

category_id             0
category_name           0
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

### Duplicate Validation ( Rows )

In [32]:
df_categories.duplicated().sum()

np.int64(0)

In [33]:
df_categories[df_categories.duplicated()]

Empty DataFrame
Columns: [category_id, category_name, extraction_timestamp, extraction_date, data_source]
Index: []

### Unique Values

In [34]:
df_categories.nunique()

category_id             7
category_name           7
extraction_timestamp    1
extraction_date         1
data_source             1
dtype: int64

In [35]:
for col in df_categories.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_categories[col].value_counts())
    print("\n")

==================================================
Column: category_id
--------------------------------------------------
category_id
1    1
2    1
3    1
4    1
5    1
6    1
7    1
Name: count, dtype: int64


==================================================
Column: category_name
--------------------------------------------------
category_name
Children Bicycles      1
Comfort Bicycles       1
Cruisers Bicycles      1
Cyclocross Bicycles    1
Electric Bikes         1
Mountain Bikes         1
Road Bikes             1
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    7
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    7
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    7
Name: count, dtype: int64

No Action Needed

## Stores EDA

In [36]:
df_stores

,store_id,store_name,phone,email,street,city,state,zip_code,extraction_timestamp,extraction_date,data_source
0,1,Santa Cruz Bikes,(831) 476-4321,NaN,3700 Portola Drive,Santa Cruz,CA,NaN,1774518425,2026-03-26 09:47:05,Data Lake
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432.0,1774518425,2026-03-26 09:47:05,Data Lake
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088.0,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [37]:
# table summary
df_stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              3 non-null      int64
 1   store_name            3 non-null      str
 2   phone                 3 non-null      str
 3   email                 2 non-null      str
 4   street                3 non-null      str
 5   city                  3 non-null      str
 6   state                 3 non-null      str
 7   zip_code              2 non-null      float64
 8   extraction_timestamp  3 non-null      int64
 9   extraction_date       3 non-null      datetime64[s]
 10  data_source           3 non-null      str
dtypes: datetime64[s](1), float64(1), int64(2), str(7)
memory usage: 396.0 bytes

In [38]:
# numeris vars summary
df_stores.describe()

       store_id      zip_code  extraction_timestamp      extraction_date
count       3.0      2.000000          3.000000e+00                    3
mean        2.0  43260.000000          1.774518e+09  2026-03-26 09:47:05
min         1.0  11432.000000          1.774518e+09  2026-03-26 09:47:05
25%         1.5  27346.000000          1.774518e+09  2026-03-26 09:47:05
50%         2.0  43260.000000          1.774518e+09  2026-03-26 09:47:05
75%         2.5  59174.000000          1.774518e+09  2026-03-26 09:47:05
max         3.0  75088.000000          1.774518e+09  2026-03-26 09:47:05
std         1.0  45011.589263          0.000000e+00                  NaN

In [39]:
rows,cols=df_stores.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 3
num of columns = 11

### Null Checks

In [40]:
t_nulls = df_stores.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_stores.isna().sum()

total_num_of_nulls = 2
====================
nulls per column

store_id                0
store_name              0
phone                   0
email                   1
street                  0
city                    0
state                   0
zip_code                1
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

### Duplicate Validation ( Rows )

In [41]:
df_stores.duplicated().sum()

np.int64(0)

In [42]:
df_stores[df_stores.duplicated()]

Empty DataFrame
Columns: [store_id, store_name, phone, email, street, city, state, zip_code, extraction_timestamp, extraction_date, data_source]
Index: []

### Unique Values

In [43]:
df_stores.nunique()

store_id                3
store_name              3
phone                   3
email                   2
street                  3
city                    3
state                   3
zip_code                2
extraction_timestamp    1
extraction_date         1
data_source             1
dtype: int64

In [44]:
for col in df_stores.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_stores[col].value_counts())
    print("\n")

==================================================
Column: store_id
--------------------------------------------------
store_id
1    1
2    1
3    1
Name: count, dtype: int64


==================================================
Column: store_name
--------------------------------------------------
store_name
Santa Cruz Bikes    1
Baldwin Bikes       1
Rowlett Bikes       1
Name: count, dtype: int64


==================================================
Column: phone
--------------------------------------------------
phone
(831) 476-4321    1
(516) 379-8888    1
(972) 530-5555    1
Name: count, dtype: int64


==================================================
Column: email
--------------------------------------------------
email
baldwin@bikes.shop    1
rowlett@bikes.shop    1
Name: count, dtype: int64


==================================================
Column: street
--------------------------------------------------
street
3700 Portola Drive     1
4200 Chestnut Lane     1
8000 Fairway Avenue    1
Name: count, dtype: int64


==================================================
Column: city
--------------------------------------------------
city
Santa Cruz    1
Baldwin       1
Rowlett       1
Name: count, dtype: int64


==================================================
Column: state
--------------------------------------------------
state
CA    1
NY    1
TX    1
Name: count, dtype: int64


==================================================
Column: zip_code
--------------------------------------------------
zip_code
11432.0    1
75088.0    1
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    3
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    3
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    3
Name: count, dtype: int64

No Action Needed

## Staffs EDA

In [45]:
df_staffs

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id,extraction_timestamp,extraction_date,data_source
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,NaN,1,NaN,NaN,1774518425,2026-03-26 09:47:05,Data Lake
1,2,Mireya,NaN,mireya.copeland@bikes.shop,(831) 555-5555,1,1.0,1.0,1774518425,2026-03-26 09:47:05,Data Lake
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1.0,2.0,1774518425,2026-03-26 09:47:05,Data Lake
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1.0,2.0,1774518425,2026-03-26 09:47:05,Data Lake
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2.0,1.0,1774518425,2026-03-26 09:47:05,Data Lake
5,6,Marcelene,Boyer,NaN,(516) 379-4445,1,2.0,5.0,1774518425,2026-03-26 09:47:05,Data Lake
6,7,Venita,Daniel,venita.daniel@bikes.shop,NaN,1,2.0,5.0,1774518425,2026-03-26 09:47:05,Data Lake
7,8,Kali,Vargas,kali.vargas@bikes.shop,(972) 530-5555,1,3.0,1.0,1774518425,2026-03-26 09:47:05,Data Lake
8,9,Layla,Terrell,layla.terrell@bikes.shop,(972) 530-5556,1,3.0,7.0,1774518425,2026-03-26 09:47:05,Data Lake
9,10,Bernardine,Houston,bernardine.houston@bikes.shop,(972) 530-5557,1,3.0,7.0,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [46]:
# table summary
df_staffs.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   staff_id              10 non-null     int64
 1   first_name            10 non-null     str
 2   last_name             9 non-null      str
 3   email                 9 non-null      str
 4   phone                 8 non-null      str
 5   active                10 non-null     int64
 6   store_id              9 non-null      float64
 7   manager_id            9 non-null      float64
 8   extraction_timestamp  10 non-null     int64
 9   extraction_date       10 non-null     datetime64[s]
 10  data_source           10 non-null     str
dtypes: datetime64[s](1), float64(2), int64(3), str(5)
memory usage: 1012.0 bytes

In [47]:
# numeris vars summary
df_staffs.describe()

,staff_id,active,store_id,manager_id,extraction_timestamp,extraction_date
count,10.00000,10.0,9.000000,9.000000,1.000000e+01,10
mean,5.50000,1.0,2.000000,3.444444,1.774518e+09,2026-03-26 09:47:05
min,1.00000,1.0,1.000000,1.000000,1.774518e+09,2026-03-26 09:47:05
25%,3.25000,1.0,1.000000,1.000000,1.774518e+09,2026-03-26 09:47:05
50%,5.50000,1.0,2.000000,2.000000,1.774518e+09,2026-03-26 09:47:05
75%,7.75000,1.0,3.000000,5.000000,1.774518e+09,2026-03-26 09:47:05
max,10.00000,1.0,3.000000,7.000000,1.774518e+09,2026-03-26 09:47:05
std,3.02765,0.0,0.866025,2.554952,0.000000e+00,NaN

In [48]:
rows,cols=df_staffs.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 10
num of columns = 11

### Null Checks

In [49]:
t_nulls = df_staffs.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_staffs.isna().sum()

total_num_of_nulls = 6
====================
nulls per column

staff_id                0
first_name              0
last_name               1
email                   1
phone                   2
active                  0
store_id                1
manager_id              1
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

### Duplicate Validation ( Rows )

In [50]:
df_staffs.duplicated().sum()

np.int64(0)

In [51]:
df_staffs[df_staffs.duplicated()]

Empty DataFrame
Columns: [staff_id, first_name, last_name, email, phone, active, store_id, manager_id, extraction_timestamp, extraction_date, data_source]
Index: []

### Unique Values

In [52]:
df_staffs.nunique()

staff_id                10
first_name              10
last_name                9
email                    9
phone                    8
active                   1
store_id                 3
manager_id               4
extraction_timestamp     1
extraction_date          1
data_source              1
dtype: int64

In [53]:
for col in df_staffs.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_staffs[col].value_counts())
    print("\n")

==================================================
Column: staff_id
--------------------------------------------------
staff_id
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
Name: count, dtype: int64


==================================================
Column: first_name
--------------------------------------------------
first_name
Fabiola       1
Mireya        1
Genna         1
Virgie        1
Jannette      1
Marcelene     1
Venita        1
Kali          1
Layla         1
Bernardine    1
Name: count, dtype: int64


==================================================
Column: last_name
--------------------------------------------------
last_name
Jackson    1
Serrano    1
Wiggins    1
David      1
Boyer      1
Daniel     1
Vargas     1
Terrell    1
Houston    1
Name: count, dtype: int64


==================================================
Column: email
--------------------------------------------------
email
fabiola.jackson@bikes.shop       1
mireya.copeland@bikes.shop       1
genna.serrano@bikes.shop         1
virgie.wiggins@bikes.shop        1
jannette.david@bikes.shop        1
venita.daniel@bikes.shop         1
kali.vargas@bikes.shop           1
layla.terrell@bikes.shop         1
bernardine.houston@bikes.shop    1
Name: count, dtype: int64


==================================================
Column: phone
--------------------------------------------------
phone
(831) 555-5555    1
(831) 555-5556    1
(831) 555-5557    1
(516) 379-4444    1
(516) 379-4445    1
(972) 530-5555    1
(972) 530-5556    1
(972) 530-5557    1
Name: count, dtype: int64


==================================================
Column: active
--------------------------------------------------
active
1    10
Name: count, dtype: int64


==================================================
Column: store_id
--------------------------------------------------
store_id
1.0    3
2.0    3
3.0    3
Name: count, dtype: int64


==================================================
Column: manager_id
--------------------------------------------------
manager_id
1.0    3
2.0    2
5.0    2
7.0    2
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    10
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    10
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    10
Name: count, dtype: int64

No Actions Needed

## Stocks EDA

In [54]:
df_stocks

,store_id,product_id,quantity,extraction_timestamp,extraction_date,data_source
0,1,1,27,1774518425,2026-03-26 09:47:05,Data Lake
1,1,2,5,1774518425,2026-03-26 09:47:05,Data Lake
2,1,3,6,1774518425,2026-03-26 09:47:05,Data Lake
3,1,4,23,1774518425,2026-03-26 09:47:05,Data Lake
4,1,5,22,1774518425,2026-03-26 09:47:05,Data Lake
...,...,...,...,...,...,...
934,3,309,30,1774518425,2026-03-26 09:47:05,Data Lake
935,3,310,8,1774518425,2026-03-26 09:47:05,Data Lake
936,3,311,23,1774518425,2026-03-26 09:47:05,Data Lake
937,3,312,18,1774518425,2026-03-26 09:47:05,Data Lake
938,3,313,0,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [55]:
# table summary
df_stocks.info()

<class 'pandas.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              939 non-null    int64
 1   product_id            939 non-null    int64
 2   quantity              939 non-null    int64
 3   extraction_timestamp  939 non-null    int64
 4   extraction_date       939 non-null    datetime64[s]
 5   data_source           939 non-null    str
dtypes: datetime64[s](1), int64(4), str(1)
memory usage: 44.1 KB

In [56]:
# numeris vars summary
df_stocks.describe()

,store_id,product_id,quantity,extraction_timestamp,extraction_date
count,939.000000,939.000000,939.000000,9.390000e+02,939
mean,2.000000,157.000000,14.388711,1.774518e+09,2026-03-26 09:47:05
min,1.000000,1.000000,0.000000,1.774518e+09,2026-03-26 09:47:05
25%,1.000000,79.000000,7.000000,1.774518e+09,2026-03-26 09:47:05
50%,2.000000,157.000000,14.000000,1.774518e+09,2026-03-26 09:47:05
75%,3.000000,235.000000,22.000000,1.774518e+09,2026-03-26 09:47:05
max,3.000000,313.000000,30.000000,1.774518e+09,2026-03-26 09:47:05
std,0.816932,90.403007,8.832070,0.000000e+00,NaN

In [57]:
rows,cols=df_stocks.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 939
num of columns = 6

### Null Checks

In [58]:
t_nulls = df_stocks.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_stocks.isna().sum()

total_num_of_nulls = 0
====================
nulls per column

store_id                0
product_id              0
quantity                0
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

### Duplicate Validation ( Rows )

In [59]:
df_stocks.duplicated().sum()

np.int64(0)

In [60]:
df_stocks[df_stocks.duplicated()]

Empty DataFrame
Columns: [store_id, product_id, quantity, extraction_timestamp, extraction_date, data_source]
Index: []

### Unique Values

In [61]:
df_stocks.nunique()

store_id                  3
product_id              313
quantity                 31
extraction_timestamp      1
extraction_date           1
data_source               1
dtype: int64

In [62]:
for col in df_stocks.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_stocks[col].value_counts())
    print("\n")

==================================================
Column: store_id
--------------------------------------------------
store_id
1    313
2    313
3    313
Name: count, dtype: int64


==================================================
Column: product_id
--------------------------------------------------
product_id
1      3
2      3
3      3
4      3
5      3
      ..
309    3
310    3
311    3
312    3
313    3
Name: count, Length: 313, dtype: int64


==================================================
Column: quantity
--------------------------------------------------
quantity
1     40
22    39
23    38
6     36
8     36
11    36
4     35
15    34
16    34
3     34
12    34
13    33
7     33
2     32
10    32
20    30
17    30
29    29
18    29
9     28
28    27
21    26
25    26
0     25
30    25
27    24
5     24
24    24
19    24
26    23
14    19
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    939
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    939
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    939
Name: count, dtype: int64

No Action Needed
Note : Products from ID 314 : 334 Dont Exist in This Table

## Brands EDA

In [63]:
df_brands

,brand_id,brand_name,extraction_timestamp,extraction_date,data_source
0,1,Electra,1774518425,2026-03-26 09:47:05,Data Lake
1,2,Haro,1774518425,2026-03-26 09:47:05,Data Lake
2,3,Heller,1774518425,2026-03-26 09:47:05,Data Lake
3,4,Pure Cycles,1774518425,2026-03-26 09:47:05,Data Lake
4,5,Ritchey,1774518425,2026-03-26 09:47:05,Data Lake
5,6,Strider,1774518425,2026-03-26 09:47:05,Data Lake
6,7,Sun Bicycles,1774518425,2026-03-26 09:47:05,Data Lake
7,8,Surly,1774518425,2026-03-26 09:47:05,Data Lake
8,9,Trek,1774518425,2026-03-26 09:47:05,Data Lake

### Data Validation

In [64]:
# table summary
df_brands.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand_id              9 non-null      int64
 1   brand_name            9 non-null      str
 2   extraction_timestamp  9 non-null      int64
 3   extraction_date       9 non-null      datetime64[s]
 4   data_source           9 non-null      str
dtypes: datetime64[s](1), int64(2), str(2)
memory usage: 492.0 bytes

In [65]:
# numeris vars summary
df_brands.describe()

       brand_id  extraction_timestamp      extraction_date
count  9.000000          9.000000e+00                    9
mean   5.000000          1.774518e+09  2026-03-26 09:47:05
min    1.000000          1.774518e+09  2026-03-26 09:47:05
25%    3.000000          1.774518e+09  2026-03-26 09:47:05
50%    5.000000          1.774518e+09  2026-03-26 09:47:05
75%    7.000000          1.774518e+09  2026-03-26 09:47:05
max    9.000000          1.774518e+09  2026-03-26 09:47:05
std    2.738613          0.000000e+00                  NaN

In [66]:
rows,cols=df_brands.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 9
num of columns = 5

### Null Checks

In [67]:
t_nulls = df_brands.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_brands.isna().sum()

total_num_of_nulls = 0
====================
nulls per column

brand_id                0
brand_name              0
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

### Duplicate Validation

In [68]:
df_brands.duplicated().sum()

np.int64(0)

In [69]:
df_brands[df_brands.duplicated()]

Empty DataFrame
Columns: [brand_id, brand_name, extraction_timestamp, extraction_date, data_source]
Index: []

### Unique Values

In [70]:
df_brands.nunique()

brand_id                9
brand_name              9
extraction_timestamp    1
extraction_date         1
data_source             1
dtype: int64

In [71]:
for col in df_brands.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_brands[col].value_counts())
    print("\n")

==================================================
Column: brand_id
--------------------------------------------------
brand_id
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: count, dtype: int64


==================================================
Column: brand_name
--------------------------------------------------
brand_name
Electra         1
Haro            1
Heller          1
Pure Cycles     1
Ritchey         1
Strider         1
Sun Bicycles    1
Surly           1
Trek            1
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1774518425    9
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2026-03-26 09:47:05    9
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
Data Lake    9
Name: count, dtype: int64

No Action Needed

# Actions

## Products

### Remove Duplicated Rows

In [72]:
len(df_products)

334

In [73]:
df_products.duplicated().sum()

np.int64(13)

In [74]:
df_products = df_products.drop_duplicates()

In [75]:
len(df_products)

321

In [76]:
df_products.duplicated().sum()

np.int64(0)

# Exrat Checks

In [85]:
# CHeck integrity between store id in [df staff , df stores]
print(df_staffs["store_id"].isin(df_stores["store_id"]).all() )

count_invalid = (~df_staffs["store_id"].isin(df_stores["store_id"])).sum()
print(count_invalid)

invalid_values = df_staffs.loc[~df_staffs["store_id"].isin(df_stores["store_id"]),"store_id"].unique()
print(invalid_values)

False
1
[nan]

In [88]:
# CHeck integrity between store id in [df stores , df stocks]
print(df_stocks["store_id"].isin(df_stores["store_id"]).all() )

count_invalid = (~df_stocks["store_id"].isin(df_stores["store_id"])).sum()
print(count_invalid)

invalid_values = df_stocks.loc[~df_stocks["store_id"].isin(df_stores["store_id"]),"store_id"].unique()
print(invalid_values)

True
0
[]

In [86]:
# CHeck integrity between product id in [df stocks , df products]
print(df_stocks["product_id"].isin(df_products["product_id"]).all() )

count_invalid = (~df_stocks["product_id"].isin(df_products["product_id"])).sum()
print(count_invalid)

invalid_values = df_stocks.loc[~df_stocks["store_id"].isin(df_products["product_id"]),"product_id"].unique()
print(invalid_values)

True
0
[]

In [87]:
# CHeck integrity between brand id in [df brands , df products]
print(df_products["brand_id"].isin(df_brands["brand_id"]).all() )

count_invalid = (~df_products["brand_id"].isin(df_brands["brand_id"])).sum()
print(count_invalid)

invalid_values = df_products.loc[~df_products["brand_id"].isin(df_brands["brand_id"]),"brand_id"].unique()
print(invalid_values)

True
0
[]

In [90]:
# CHeck integrity between category id in [df categories , df products]
print(df_products["category_id"].isin(df_categories["category_id"]).all() )

count_invalid = (~df_products["category_id"].isin(df_categories["category_id"])).sum()
print(count_invalid)

invalid_values = df_products.loc[~df_products["category_id"].isin(df_categories["category_id"]),"category_id"].unique()
print(invalid_values)

True
0
[]

# Export Files

In [80]:
for i in df_names:
    name = i.replace("df_","")
    print(name)

brands
categories
customers
products
staffs
stocks
stores

In [85]:
for name in df_names:
    df = globals()[name]
    
    clean_name = name.replace("df_","")
    
    df.to_csv(f"../data/staging_1/{clean_name}.csv", index=False)
    print(f" saved : {clean_name}.csv")

 saved : brands.csv
 saved : categories.csv
 saved : customers.csv
 saved : products.csv
 saved : staffs.csv
 saved : stocks.csv
 saved : stores.csv