ReadMe

Database
├── Orders EDA
├── Order Items EDA
├── Checks Between Database Files
├── Check Integrity Between DB and DL Files
├── Actions
│   ├── Aggregate Rows (order_id + product_id)
│   └── Delete Invalid order_id
└── Export Files

# Orders EDA

In [130]:
import pandas as pd 
from glob import glob
import os

In [131]:
df_orders = pd.read_csv("../data/intermediate/orders.csv")

In [132]:
df_orders

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,extraction_date,data_source
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,1714563448,SQL-Server\r
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6,1714563448,SQL-Server\r
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7,1714563448,SQL-Server\r
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,1714563448,SQL-Server\r
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6,1714563448,SQL-Server\r
...,...,...,...,...,...,...,...,...,...,...
1440,1474,816,4,2018-03-30,2018-04-01,2018-04-02,1,3,1714563448,SQL-Server\r
1441,1475,112,4,2018-03-30,2018-04-01,2018-03-31,2,6,1714563448,SQL-Server\r
1442,1476,35,4,2018-03-31,2018-04-01,2018-04-01,2,7,1714563448,SQL-Server\r
1443,1477,180,4,2018-03-31,2018-04-03,2018-04-01,2,6,1714563448,SQL-Server\r
1444,1478,392,4,2018-03-31,2018-04-02,2018-04-02,2,6,1714563448,SQL-Server

In [133]:
df_orders.rename(columns={"extraction_date": "extraction_timestamp"}, inplace=True)

In [134]:
df_orders

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,extraction_timestamp,data_source
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,1714563448,SQL-Server\r
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6,1714563448,SQL-Server\r
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7,1714563448,SQL-Server\r
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,1714563448,SQL-Server\r
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6,1714563448,SQL-Server\r
...,...,...,...,...,...,...,...,...,...,...
1440,1474,816,4,2018-03-30,2018-04-01,2018-04-02,1,3,1714563448,SQL-Server\r
1441,1475,112,4,2018-03-30,2018-04-01,2018-03-31,2,6,1714563448,SQL-Server\r
1442,1476,35,4,2018-03-31,2018-04-01,2018-04-01,2,7,1714563448,SQL-Server\r
1443,1477,180,4,2018-03-31,2018-04-03,2018-04-01,2,6,1714563448,SQL-Server\r
1444,1478,392,4,2018-03-31,2018-04-02,2018-04-02,2,6,1714563448,SQL-Server

In [135]:
df_orders["extraction_date"] = pd.to_datetime(df_orders["extraction_timestamp"], unit="s")

In [136]:
col = df_orders.pop("extraction_date")
df_orders.insert(9, "extraction_date", col)

In [137]:
df_orders

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,extraction_timestamp,extraction_date,data_source
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,1714563448,2024-05-01 11:37:28,SQL-Server\r
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6,1714563448,2024-05-01 11:37:28,SQL-Server\r
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7,1714563448,2024-05-01 11:37:28,SQL-Server\r
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,1714563448,2024-05-01 11:37:28,SQL-Server\r
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6,1714563448,2024-05-01 11:37:28,SQL-Server\r
...,...,...,...,...,...,...,...,...,...,...,...
1440,1474,816,4,2018-03-30,2018-04-01,2018-04-02,1,3,1714563448,2024-05-01 11:37:28,SQL-Server\r
1441,1475,112,4,2018-03-30,2018-04-01,2018-03-31,2,6,1714563448,2024-05-01 11:37:28,SQL-Server\r
1442,1476,35,4,2018-03-31,2018-04-01,2018-04-01,2,7,1714563448,2024-05-01 11:37:28,SQL-Server\r
1443,1477,180,4,2018-03-31,2018-04-03,2018-04-01,2,6,1714563448,2024-05-01 11:37:28,SQL-Server\r
1444,1478,392,4,2018-03-31,2018-04-02,2018-04-02,2,6,1714563448,2024-05-01 11:37:28,SQL-Server

In [138]:
df_orders["data_source"] = df_orders["data_source"].str.strip()

In [139]:
df_orders

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,extraction_timestamp,extraction_date,data_source
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,1714563448,2024-05-01 11:37:28,SQL-Server
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6,1714563448,2024-05-01 11:37:28,SQL-Server
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7,1714563448,2024-05-01 11:37:28,SQL-Server
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,1714563448,2024-05-01 11:37:28,SQL-Server
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6,1714563448,2024-05-01 11:37:28,SQL-Server
...,...,...,...,...,...,...,...,...,...,...,...
1440,1474,816,4,2018-03-30,2018-04-01,2018-04-02,1,3,1714563448,2024-05-01 11:37:28,SQL-Server
1441,1475,112,4,2018-03-30,2018-04-01,2018-03-31,2,6,1714563448,2024-05-01 11:37:28,SQL-Server
1442,1476,35,4,2018-03-31,2018-04-01,2018-04-01,2,7,1714563448,2024-05-01 11:37:28,SQL-Server
1443,1477,180,4,2018-03-31,2018-04-03,2018-04-01,2,6,1714563448,2024-05-01 11:37:28,SQL-Server
1444,1478,392,4,2018-03-31,2018-04-02,2018-04-02,2,6,1714563448,2024-05-01 11:37:28,SQL-Server

## Data Validation

In [140]:
# table summary
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              1445 non-null   int64
 1   customer_id           1445 non-null   int64
 2   order_status          1445 non-null   int64
 3   order_date            1445 non-null   str
 4   required_date         1445 non-null   str
 5   shipped_date          1445 non-null   str
 6   store_id              1445 non-null   int64
 7   staff_id              1445 non-null   int64
 8   extraction_timestamp  1445 non-null   int64
 9   extraction_date       1445 non-null   datetime64[s]
 10  data_source           1445 non-null   str
dtypes: datetime64[s](1), int64(6), str(4)
memory usage: 124.3 KB

In [141]:
# numeris vars summary
df_orders.describe()

,order_id,customer_id,order_status,store_id,staff_id,extraction_timestamp,extraction_date
count,1445.000000,1445.000000,1445.0,1445.000000,1445.000000,1.445000e+03,1445
mean,740.689965,723.000000,4.0,1.901730,5.905882,1.714563e+09,2024-05-01 11:37:28
min,1.000000,1.000000,4.0,1.000000,2.000000,1.714563e+09,2024-05-01 11:37:28
25%,372.000000,362.000000,4.0,2.000000,6.000000,1.714563e+09,2024-05-01 11:37:28
50%,741.000000,723.000000,4.0,2.000000,6.000000,1.714563e+09,2024-05-01 11:37:28
75%,1113.000000,1084.000000,4.0,2.000000,7.000000,1.714563e+09,2024-05-01 11:37:28
max,1478.000000,1445.000000,4.0,3.000000,9.000000,1.714563e+09,2024-05-01 11:37:28
std,427.735174,417.279882,0.0,0.534182,1.846461,0.000000e+00,NaN

In [142]:
rows,cols=df_orders.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 1445
num of columns = 11

## Null Checks

In [143]:
t_nulls = df_orders.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_orders.isna().sum()

total_num_of_nulls = 0
====================
nulls per column

order_id                0
customer_id             0
order_status            0
order_date              0
required_date           0
shipped_date            0
store_id                0
staff_id                0
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

## Duplicate Validation ( Rows )

In [144]:
df_orders.duplicated().sum()

np.int64(0)

In [145]:
df_orders[df_orders.duplicated()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id, extraction_timestamp, extraction_date, data_source]
Index: []

## Unique Values

In [146]:
df_orders.nunique()

order_id                1445
customer_id             1445
order_status               1
order_date               680
required_date            690
shipped_date             675
store_id                   3
staff_id                   6
extraction_timestamp       1
extraction_date            1
data_source                1
dtype: int64

In [147]:
for col in df_orders.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_orders[col].value_counts())
    print("\n")

==================================================
Column: order_id
--------------------------------------------------
order_id
1       1
2       1
3       1
4       1
5       1
       ..
1474    1
1475    1
1476    1
1477    1
1478    1
Name: count, Length: 1445, dtype: int64


==================================================
Column: customer_id
--------------------------------------------------
customer_id
259     1
1212    1
523     1
175     1
1324    1
       ..
816     1
112     1
35      1
180     1
392     1
Name: count, Length: 1445, dtype: int64


==================================================
Column: order_status
--------------------------------------------------
order_status
4    1445
Name: count, dtype: int64


==================================================
Column: order_date
--------------------------------------------------
order_date
2017-10-01    8
2016-10-06    7
2017-03-09    7
2017-08-17    7
2017-08-19    7
             ..
2018-03-10    1
2018-03-23    1
2018-03-24    1
2018-03-25    1
2018-03-29    1
Name: count, Length: 680, dtype: int64


==================================================
Column: required_date
--------------------------------------------------
required_date
2017-03-01    7
2017-08-20    7
2017-10-03    7
2016-10-12    6
2017-02-08    6
             ..
2018-03-29    1
2018-03-27    1
2018-03-31    1
2018-04-03    1
2018-04-02    1
Name: count, Length: 690, dtype: int64


==================================================
Column: shipped_date
--------------------------------------------------
shipped_date
2017-10-29    8
2017-06-27    7
2016-08-18    6
2016-09-01    6
2016-10-11    6
             ..
2018-03-05    1
2018-03-12    1
2018-03-19    1
2018-03-25    1
2018-03-30    1
Name: count, Length: 675, dtype: int64


==================================================
Column: store_id
--------------------------------------------------
store_id
2    1019
1     284
3     142
Name: count, dtype: int64


==================================================
Column: staff_id
--------------------------------------------------
staff_id
6    521
7    498
3    147
2    137
8     71
9     71
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1714563448    1445
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2024-05-01 11:37:28    1445
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
SQL-Server    1445
Name: count, dtype: int64

## Data Integrity

In [148]:
df_orders["order_date"] = pd.to_datetime(df_orders["order_date"])
df_orders["required_date"] = pd.to_datetime(df_orders["required_date"])
df_orders["shipped_date"] = pd.to_datetime(df_orders["shipped_date"])

In [149]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              1445 non-null   int64
 1   customer_id           1445 non-null   int64
 2   order_status          1445 non-null   int64
 3   order_date            1445 non-null   datetime64[us]
 4   required_date         1445 non-null   datetime64[us]
 5   shipped_date          1445 non-null   datetime64[us]
 6   store_id              1445 non-null   int64
 7   staff_id              1445 non-null   int64
 8   extraction_timestamp  1445 non-null   int64
 9   extraction_date       1445 non-null   datetime64[s]
 10  data_source           1445 non-null   str
dtypes: datetime64[s](1), datetime64[us](3), int64(6), str(1)
memory usage: 124.3 KB

In [150]:
invalid_ship = df_orders[df_orders["shipped_date"] < df_orders["order_date"]]
invalid_ship

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id, extraction_timestamp, extraction_date, data_source]
Index: []

In [151]:
invalid_required = df_orders[df_orders["required_date"] < df_orders["order_date"]]
invalid_required

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id, extraction_timestamp, extraction_date, data_source]
Index: []

In [152]:
invalid_late = df_orders[df_orders["shipped_date"] > df_orders["required_date"]]
invalid_late

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,extraction_timestamp,extraction_date,data_source
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,1714563448,2024-05-01 11:37:28,SQL-Server
11,12,91,4,2016-01-06,2016-01-08,2016-01-09,1,2,1714563448,2024-05-01 11:37:28,SQL-Server
13,14,258,4,2016-01-09,2016-01-11,2016-01-12,1,3,1714563448,2024-05-01 11:37:28,SQL-Server
14,15,450,4,2016-01-09,2016-01-10,2016-01-12,2,7,1714563448,2024-05-01 11:37:28,SQL-Server
19,20,923,4,2016-01-14,2016-01-16,2016-01-17,1,2,1714563448,2024-05-01 11:37:28,SQL-Server
...,...,...,...,...,...,...,...,...,...,...,...
1433,1467,152,4,2018-03-26,2018-03-27,2018-03-29,2,7,1714563448,2024-05-01 11:37:28,SQL-Server
1435,1469,1135,4,2018-03-27,2018-03-28,2018-03-30,3,8,1714563448,2024-05-01 11:37:28,SQL-Server
1438,1472,114,4,2018-03-29,2018-03-30,2018-03-31,2,6,1714563448,2024-05-01 11:37:28,SQL-Server
1439,1473,302,4,2018-03-30,2018-04-01,2018-04-02,1,2,1714563448,2024-05-01 11:37:28,SQL-Server
1440,1474,816,4,2018-03-30,2018-04-01,2018-04-02,1,3,1714563448,2024-05-01 11:37:28,SQL-Server

There are alot of late shipping ( could be useful at the analysis step )

# Order Items EDA

In [153]:
df_order_items = pd.read_csv("../data/intermediate/order_items.csv")

In [154]:
df_order_items

,order_id,item_id,product_id,quantity,list_price,discount,extraction_date,data_source
0,1,1,20,1,599.99,0.20,1714563465,SQL-Server\r
1,1,2,8,2,1799.99,0.07,1714563465,SQL-Server\r
2,1,3,10,2,1549.00,0.05,1714563465,SQL-Server\r
3,1,4,16,2,599.99,0.05,1714563465,SQL-Server\r
4,1,5,4,1,2899.99,0.20,1714563465,SQL-Server\r
...,...,...,...,...,...,...,...,...
4759,1615,9,182,1,2499.99,0.20,1714563465,SQL-Server\r
4760,1612,sz258l',289,2,319.99,0.05,1714563465,SQL-Server\r
4761,1612,sz756l',101,2,339.99,0.20,1714563465,SQL-Server\r
4762,1612,sz758k',293,2,319.99,0.07,1714563465,SQL-Server\r
4763,1612,sz758l',60,1,1559.99,0.10,1714563465,SQL-Server

In [155]:
df_order_items.rename(columns={"extraction_date": "extraction_timestamp"}, inplace=True)

In [156]:
df_order_items

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,data_source
0,1,1,20,1,599.99,0.20,1714563465,SQL-Server\r
1,1,2,8,2,1799.99,0.07,1714563465,SQL-Server\r
2,1,3,10,2,1549.00,0.05,1714563465,SQL-Server\r
3,1,4,16,2,599.99,0.05,1714563465,SQL-Server\r
4,1,5,4,1,2899.99,0.20,1714563465,SQL-Server\r
...,...,...,...,...,...,...,...,...
4759,1615,9,182,1,2499.99,0.20,1714563465,SQL-Server\r
4760,1612,sz258l',289,2,319.99,0.05,1714563465,SQL-Server\r
4761,1612,sz756l',101,2,339.99,0.20,1714563465,SQL-Server\r
4762,1612,sz758k',293,2,319.99,0.07,1714563465,SQL-Server\r
4763,1612,sz758l',60,1,1559.99,0.10,1714563465,SQL-Server

In [157]:
df_order_items["extraction_date"] = pd.to_datetime(df_order_items["extraction_timestamp"], unit="s")

In [158]:
col = df_order_items.pop("extraction_date")
df_order_items.insert(7, "extraction_date", col)

In [159]:
df_order_items

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,extraction_date,data_source
0,1,1,20,1,599.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server\r
1,1,2,8,2,1799.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server\r
2,1,3,10,2,1549.00,0.05,1714563465,2024-05-01 11:37:45,SQL-Server\r
3,1,4,16,2,599.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server\r
4,1,5,4,1,2899.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server\r
...,...,...,...,...,...,...,...,...,...
4759,1615,9,182,1,2499.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server\r
4760,1612,sz258l',289,2,319.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server\r
4761,1612,sz756l',101,2,339.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server\r
4762,1612,sz758k',293,2,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server\r
4763,1612,sz758l',60,1,1559.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server

In [160]:
df_order_items["data_source"] = df_order_items["data_source"].str.strip()

In [161]:
df_order_items

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,extraction_date,data_source
0,1,1,20,1,599.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
1,1,2,8,2,1799.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
2,1,3,10,2,1549.00,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
3,1,4,16,2,599.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4,1,5,4,1,2899.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
...,...,...,...,...,...,...,...,...,...
4759,1615,9,182,1,2499.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
4760,1612,sz258l',289,2,319.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4761,1612,sz756l',101,2,339.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
4762,1612,sz758k',293,2,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
4763,1612,sz758l',60,1,1559.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server

## Data Validation

In [162]:
# table summary
df_order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 4764 entries, 0 to 4763
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              4764 non-null   int64
 1   item_id               4764 non-null   str
 2   product_id            4764 non-null   int64
 3   quantity              4764 non-null   int64
 4   list_price            4764 non-null   float64
 5   discount              4764 non-null   float64
 6   extraction_timestamp  4764 non-null   int64
 7   extraction_date       4764 non-null   datetime64[s]
 8   data_source           4764 non-null   str
dtypes: datetime64[s](1), float64(2), int64(4), str(2)
memory usage: 335.1 KB

In [163]:
# numeris vars summary
df_order_items.describe()

,order_id,product_id,quantity,list_price,discount,extraction_timestamp,extraction_date
count,4764.000000,4764.000000,4764.000000,4764.000000,4764.000000,4.764000e+03,4764
mean,824.029597,59.797229,1.499790,1443.206008,0.105424,1.714563e+09,2024-05-01 11:37:45
min,1.000000,2.000000,1.000000,89.990000,0.050000,1.714563e+09,2024-05-01 11:37:45
25%,425.000000,14.000000,1.000000,429.000000,0.050000,1.714563e+09,2024-05-01 11:37:45
50%,834.000000,29.000000,1.000000,599.990000,0.085000,1.714563e+09,2024-05-01 11:37:45
75%,1228.250000,85.000000,2.000000,1549.000000,0.200000,1.714563e+09,2024-05-01 11:37:45
max,1615.000000,315.000000,2.000000,259999.000000,0.200000,1.714563e+09,2024-05-01 11:37:45
std,466.796271,67.769121,0.500052,5012.578599,0.058153,0.000000e+00,NaN

In [164]:
rows,cols=df_order_items.shape
print(f"num of rows = {rows}")
print(f"num of columns = {cols}")

num of rows = 4764
num of columns = 9

## Null Checks

In [165]:
t_nulls = df_order_items.isna().sum().sum()
print(f"total_num_of_nulls = {t_nulls}")
print("="*20)
print("nulls per column")
df_order_items.isna().sum()

total_num_of_nulls = 0
====================
nulls per column

order_id                0
item_id                 0
product_id              0
quantity                0
list_price              0
discount                0
extraction_timestamp    0
extraction_date         0
data_source             0
dtype: int64

## Duplicate Validation ( Rows )

In [166]:
df_order_items.duplicated().sum()

np.int64(34)

In [167]:
df_order_items[df_order_items.duplicated()]

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,extraction_date,data_source
11,2,2,16,2,599.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
12,3,1,3,1,999.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
23,6,5,9,2,2999.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
24,7,1,15,1,529.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
25,7,2,3,1,999.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
26,7,3,17,2,429.00,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
2721,945,5,50,2,5999.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
2722,946,1,7,1,3999.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
2723,946,2,85,2,329.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
2724,946,3,62,1,3499.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
2725,946,4,22,2,269.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
2726,946,5,56,2,5499.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
2727,947,1,32,1,469.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
2728,947,2,42,2,2299.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
2729,947,3,44,1,539.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
2730,948,1,23,2,299.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
2731,948,2,20,2,599.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
2732,948,3,101,1,339.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
2733,948,4,92,2,209.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
2734,948,5,72,2,619.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
4255,1453,1,89,2,209.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
4256,1454,1,283,1,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
4257,1454,2,35,2,832.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
4258,1454,3,124,1,1499.00,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
4259,1454,4,38,2,549.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4260,1455,1,101,2,339.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4261,1455,2,254,1,749.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
4744,1612,2,289,2,319.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4745,1612,3,101,2,339.99,0.20,1714563465,2024-05-01 11:37:45,SQL-Server
4746,1612,4,293,2,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
4747,1612,5,60,1,1559.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
4748,1613,1,153,1,4999.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
4749,1613,2,283,2,319.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4750,1614,1,124,1,1499.00,0.07,1714563465,2024-05-01 11:37:45,SQL-Server

In [168]:
len(df_order_items[df_order_items.duplicated(keep=False)])

68

In [169]:
df_order_items[df_order_items.duplicated(keep=False)].sort_values(by="product_id")

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,extraction_date,data_source
7,3,1,3,1,999.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
12,3,1,3,1,999.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
21,7,2,3,1,999.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
25,7,2,3,1,999.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
2708,946,1,7,1,3999.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
...,...,...,...,...,...,...,...,...,...
4256,1454,1,283,1,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
4744,1612,2,289,2,319.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4737,1612,2,289,2,319.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server
4746,1612,4,293,2,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server
4739,1612,4,293,2,319.99,0.07,1714563465,2024-05-01 11:37:45,SQL-Server

Action Needed Here
Remove Duplicates 
OR 
Aggregation

## Unique Values

In [170]:
df_order_items.nunique()

order_id                1615
item_id                   14
product_id               307
quantity                   2
list_price               123
discount                   4
extraction_timestamp       1
extraction_date            1
data_source                1
dtype: int64

In [171]:
for col in df_order_items.columns:
    print("=" * 50)
    print(f"Column: {col}")
    print("-" * 50)
    print(df_order_items[col].value_counts())
    print("\n")

==================================================
Column: order_id
--------------------------------------------------
order_id
1612    13
946     10
948     10
1454     8
6        6
        ..
1599     1
1603     1
1604     1
1607     1
1608     1
Name: count, Length: 1615, dtype: int64


==================================================
Column: item_id
--------------------------------------------------
item_id
1          1625
2          1336
3           957
4           585
5           252
60            1
14            1
22            1
17            1
9             1
sz258l'       1
sz756l'       1
sz758k'       1
sz758l'       1
Name: count, dtype: int64


==================================================
Column: product_id
--------------------------------------------------
product_id
6      110
12     104
13     103
9      102
7      102
      ...
279      1
312      1
212      1
211      1
176      1
Name: count, Length: 307, dtype: int64


==================================================
Column: quantity
--------------------------------------------------
quantity
1    2383
2    2381
Name: count, dtype: int64


==================================================
Column: list_price
--------------------------------------------------
list_price
269.99      383
599.99      295
549.99      211
469.99      176
299.99      173
           ...
44999.00      1
399.99        1
1299.99       1
1259.90       1
389.99        1
Name: count, Length: 123, dtype: int64


==================================================
Column: discount
--------------------------------------------------
discount
0.20    1216
0.05    1215
0.07    1167
0.10    1166
Name: count, dtype: int64


==================================================
Column: extraction_timestamp
--------------------------------------------------
extraction_timestamp
1714563465    4764
Name: count, dtype: int64


==================================================
Column: extraction_date
--------------------------------------------------
extraction_date
2024-05-01 11:37:45    4764
Name: count, dtype: int64


==================================================
Column: data_source
--------------------------------------------------
data_source
SQL-Server    4764
Name: count, dtype: int64

# Checks Between DB Files

In [172]:
# CHeck integrity between order id in [df orders(DB) , df order_itmes(DB)]
print(df_order_items["order_id"].isin(df_orders["order_id"]).all() )

count_invalid = (~df_order_items["order_id"].isin(df_orders["order_id"])).sum()
print(count_invalid)

invalid_values = df_order_items.loc[~df_order_items["order_id"].isin(df_orders["order_id"]),"order_id"].unique()
print(invalid_values)

False
523
[  70   76  158  185  239  246  264  349  350  357  391  407  549  582
  598  692  715  735  778  810  885  924  935 1010 1020 1047 1072 1074
 1089 1177 1234 1259 1407 1479 1480 1481 1482 1483 1484 1485 1486 1487
 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501
 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515
 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1529
 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542 1543
 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556 1557
 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570 1571
 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584 1585
 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598 1599
 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612 1613
 1614 1615]

In [173]:
df_orders[df_orders["order_id"] == 185]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id, extraction_timestamp, extraction_date, data_source]
Index: []

In [174]:
df_order_items[df_order_items["order_id"] == 185]

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,extraction_date,data_source
525,185,1,20,1,599.99,0.10,1714563465,2024-05-01 11:37:45,SQL-Server
526,185,2,8,1,1799.99,0.05,1714563465,2024-05-01 11:37:45,SQL-Server

# Checks Integrity Between DB And DL Files

In [175]:
files = glob("../data/staging_1/*.csv")
print(len(files))
print(files)

8
['../data/staging_1\\brands.csv', '../data/staging_1\\categories.csv', '../data/staging_1\\currency.csv', '../data/staging_1\\customers.csv', '../data/staging_1\\products.csv', '../data/staging_1\\staffs.csv', '../data/staging_1\\stocks.csv', '../data/staging_1\\stores.csv']

In [176]:
df_names = []

In [177]:
for i in files :
    # import file 
    df = pd.read_csv(i)

    #change name of df 
    file_name =os.path.basename(i)
    file_name = file_name.replace(".csv" , "")
    globals()[f"df_{file_name}"] = df

    # add to list
    df_names.append(f"df_{file_name}")

    #print new name
    print(f"Created: df_{file_name}")

Created: df_brands
Created: df_categories
Created: df_currency
Created: df_customers
Created: df_products
Created: df_staffs
Created: df_stocks
Created: df_stores

In [178]:
# CHeck integrity between customer id in [df customer(DL) , df orders(DB)]
print(df_customers["customer_id"].isin(df_orders["customer_id"]).all() )

count_invalid = (~df_customers["customer_id"].isin(df_orders["customer_id"])).sum()
print(count_invalid)

invalid_values = df_customers.loc[~df_customers["customer_id"].isin(df_orders["customer_id"]),"customer_id"].unique()
print(invalid_values)

True
0
[]

In [179]:
# CHeck integrity between customer id in [df staffs(DL) , df orders(DB)]
print(df_orders["staff_id"].isin(df_staffs["staff_id"]).all() )

count_invalid = (~df_orders["staff_id"].isin(df_staffs["staff_id"])).sum()
print(count_invalid)

invalid_values = df_orders.loc[~df_orders["staff_id"].isin(df_staffs["staff_id"]),"staff_id"].unique()
print(invalid_values)

True
0
[]

# Actions

## Aggregate the Rows that have same order id and product id

In [180]:
df_order_items = df_order_items.groupby(["order_id", "product_id"],as_index=False).agg({
    "quantity": "sum",
    "list_price": "first",
    "discount": "first",
    "item_id": "first",
    "extraction_timestamp": "first",
    "extraction_date": "first",
    "data_source": "first"
})

In [181]:
df_order_items

,order_id,product_id,quantity,list_price,discount,item_id,extraction_timestamp,extraction_date,data_source
0,1,4,1,2899.99,0.20,5,1714563465,2024-05-01 11:37:45,SQL-Server
1,1,8,2,1799.99,0.07,2,1714563465,2024-05-01 11:37:45,SQL-Server
2,1,10,2,1549.00,0.05,3,1714563465,2024-05-01 11:37:45,SQL-Server
3,1,16,2,599.99,0.05,4,1714563465,2024-05-01 11:37:45,SQL-Server
4,1,20,1,599.99,0.20,1,1714563465,2024-05-01 11:37:45,SQL-Server
...,...,...,...,...,...,...,...,...,...
4717,1614,159,2,2299.99,0.07,2,1714563465,2024-05-01 11:37:45,SQL-Server
4718,1614,213,4,269.99,0.20,3,1714563465,2024-05-01 11:37:45,SQL-Server
4719,1615,182,2,2499.99,0.20,60,1714563465,2024-05-01 11:37:45,SQL-Server
4720,1615,197,4,2299.99,0.20,1,1714563465,2024-05-01 11:37:45,SQL-Server
4721,1615,214,2,899.99,0.07,2,1714563465,2024-05-01 11:37:45,SQL-Server

In [182]:
df_order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              4722 non-null   int64
 1   product_id            4722 non-null   int64
 2   quantity              4722 non-null   int64
 3   list_price            4722 non-null   float64
 4   discount              4722 non-null   float64
 5   item_id               4722 non-null   str
 6   extraction_timestamp  4722 non-null   int64
 7   extraction_date       4722 non-null   datetime64[s]
 8   data_source           4722 non-null   str
dtypes: datetime64[s](1), float64(2), int64(4), str(2)
memory usage: 332.1 KB

## Delete Rows with order id dosnt exist in orders tables

In [183]:
len(df_order_items)

4722

In [184]:
df_order_items= df_order_items[
    df_order_items["order_id"].isin(df_orders["order_id"])
]

In [185]:
df_order_items

,order_id,product_id,quantity,list_price,discount,item_id,extraction_timestamp,extraction_date,data_source
0,1,4,1,2899.99,0.20,5,1714563465,2024-05-01 11:37:45,SQL-Server
1,1,8,2,1799.99,0.07,2,1714563465,2024-05-01 11:37:45,SQL-Server
2,1,10,2,1549.00,0.05,3,1714563465,2024-05-01 11:37:45,SQL-Server
3,1,16,2,599.99,0.05,4,1714563465,2024-05-01 11:37:45,SQL-Server
4,1,20,1,599.99,0.20,1,1714563465,2024-05-01 11:37:45,SQL-Server
...,...,...,...,...,...,...,...,...,...
4300,1476,191,1,2799.99,0.10,4,1714563465,2024-05-01 11:37:45,SQL-Server
4301,1476,265,2,289.99,0.10,5,1714563465,2024-05-01 11:37:45,SQL-Server
4302,1477,210,2,1549.00,0.20,1,1714563465,2024-05-01 11:37:45,SQL-Server
4303,1478,100,2,489.99,0.10,1,1714563465,2024-05-01 11:37:45,SQL-Server
4304,1478,123,1,999.99,0.20,2,1714563465,2024-05-01 11:37:45,SQL-Server

In [186]:
len(df_order_items)

4214

In [187]:
# CHeck integrity between customer id in [df staffs(DL) , df orders(DB)]
print(df_orders["staff_id"].isin(df_staffs["staff_id"]).all() )

count_invalid = (~df_orders["staff_id"].isin(df_staffs["staff_id"])).sum()
print(count_invalid)

invalid_values = df_orders.loc[~df_orders["staff_id"].isin(df_staffs["staff_id"]),"staff_id"].unique()
print(invalid_values)

True
0
[]

# Export FIles

In [188]:
df_orders.to_csv(f"../data/staging_1/orders.csv", index=False)
print(" saved :orders.csv")

 saved :orders.csv

In [189]:
df_order_items.to_csv(f"../data/staging_1/order_items.csv", index=False)
print(" saved :order_items.csv")

 saved :order_items.csv